(defun my-dpi (&optional frame)
  "Get the DPI of FRAME (or current if nil)."
  (cl-flet ((pyth (lambda (w h)
                    (sqrt (+ (* w w)
                             (* h h)))))
            (mm2in (lambda (mm)
                     (/ mm 25.4))))
    (let* ((atts (frame-monitor-attributes frame))
           (pix-w (cl-fourth (assoc 'geometry atts)))
           (pix-h (cl-fifth (assoc 'geometry atts)))
           (pix-d (pyth pix-w pix-h))
           (mm-w (cl-second (assoc 'mm-size atts)))
           (mm-h (cl-third (assoc 'mm-size atts)))
           (mm-d (pyth mm-w mm-h)))
      (/ pix-d (mm2in mm-d)))))

(defvar my-dpi-last 0)
(defun my-zoom-frm-by-dpi (&optional frame)
  "Zoom FRAME so the DPI is closer to `my-zoom-frm-wanted-dpi'."
  (interactive)
  (when (frame-size-changed-p frame)
    (let ((dpi (truncate (my-dpi nil))))
      ;;(message (format "DPI: %d" dpi))
      (when (not (eq my-dpi-last dpi))
        (message (format "DPI: %d" dpi))
        (setq my-dpi-last dpi)
        (if (< dpi 110)
            (set-face-attribute 'default nil :height 110)
          (set-face-attribute 'default nil :height 110))))))
(add-hook 'window-size-change-functions #'my-zoom-frm-by-dpi)
